### ISSUE TITLE
CascadeIndentationCheck gives false positive match in case of try-with-resources

### ISSUE THREAD

**Issue by dgroup** [yegor256/qulice#1035]
```java
try (BufferedInputStream inp = new BufferedInputStream(src.part.getInputStream());
     BufferedOutputStream out = new BufferedOutputStream(Files.newOutputStream(dest))) {
        new LengthOf(
            new TeeInput(new InputOf(inp), new OutputTo(out))
        ).intValue();
}
```
Full stacktrace
```java
[INFO] Checkstyle: src/main/java/xxx.java[76]: Indentation (17) must be same or less than previous line (12), or bigger by exactly 4 (CascadeIndentationCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.694 s
[INFO] Finished at: 2019-03-31T21:59:58+05:30
[INFO] Final Memory: 24M/573M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.18.13:check (apply-qulice-validations) on project mbox4j: Failure: There are 1 violations -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.18.13:check (apply-qulice-validations) on project mbox4j: Failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoFailureException: Failure
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:86)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:170)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: com.qulice.spi.ValidationException: There are 1 violations
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:141)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:80)
	... 24 more
```
The artifact
```xml
<plugin>
            <groupId>com.qulice</groupId>
            <artifactId>qulice-maven-plugin</artifactId>
            <version>0.18.13</version>
            <configuration>
              <license>file:${basedir}/license.txt</license>
              <lineLength>100</lineLength>
              <excludes combine.children="append">
                <exclude>findbugs:.*</exclude>
              </excludes>
            </configuration>
            <executions>
              <execution>
                <id>apply-qulice-validations</id>
                <phase>validate</phase>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
            <dependencies>
              <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>${commons-logging.version}</version>
              </dependency>
            </dependencies>
          </plugin>
```

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by dgroup** [comment]
The W/A is the following
```java
try (BufferedInputStream src = this.src(); BufferedOutputStream target = out(dest)) {
    new LengthOf(
        new TeeInput(
            new InputOf(src),
            new OutputTo(target)
        )
    ).intValue();
}
```

**Comment by yegor256** [comment]
@dgroup this is a valid complaint, I believe. This is how the code should look:

```
try (BufferedInputStream inp = new BufferedInputStream(src.part.getInputStream());
    BufferedOutputStream out = new BufferedOutputStream(Files.newOutputStream(dest))) {
    new LengthOf(
        new TeeInput(new InputOf(inp), new OutputTo(out))
    ).intValue();
}
```
