### ISSUE TITLE
FindBugsValidatorTest is ignored. Let's fix it

### ISSUE THREAD

**Issue by longtimeago** [yegor256/qulice#198]
FindBugsValidatorTest is not working because of classpath problem:

```
[WARN ] com.qulice.findbugs.FindBugsValidator: Failed to execute FindBugs:
java -classpath /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/localedata.jar:/home/ppolishchuk/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:.....

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class edu.umd.cs.findbugs.ba.AnalysisContext
    at edu.umd.cs.findbugs.FindBugs2.clearCaches(FindBugs2.java:320)
    at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:300)
    at com.qulice.findbugs.Wrap.run(Wrap.java:77)
    at com.qulice.findbugs.Wrap.main(Wrap.java:54)
```

Let's fix it and remove `@Ignore` annotation

**Comment by rabbitloveLHF** [comment]
So who can tell me how to fix this bug
